baseURL = "https://www.rohithuppala.com"
languageCode = "en-us"
title = "Rohith Uppala's Blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[params]
headTitle = "Rohith Uppala"
mainSections = ["posts"]
disqus = "rohithuppala"

[languages]
    [languages.en]
        contentDir = "content"
        languageName = "English"
        weight = 1

[[params.socials]]
name = "About Me"
link = "/about"

[[params.socials]]
name = "Github"
link = "https://github.com/rohith2506"

[[params.socials]]
name = "LinkedIn"
link = "https://linkedin.com/in/rohithuppala"

[[params.socials]]
name = "CV"
link = "https://www.dropbox.com/s/4uyljjsfxa67as0/Rohith%20Uppala%20CV.pdf?dl=0"
